# Generated by Django 6.0.4 on 2026-04-15 04:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Licence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_licence', models.CharField(choices=[('standard', 'Standard (Gratuite)'), ('premium', 'Premium (9.99€/mois)'), ('business', 'Business (49.99€/mois)')], default='standard', max_length=20)),
                ('statut', models.CharField(choices=[('active', 'Active'), ('expired', 'Expirée'), ('suspended', 'Suspendue')], default='active', max_length=20)),
                ('plafond_transaction', models.DecimalField(decimal_places=2, default=1000, max_digits=12)),
                ('plafond_journalier', models.DecimalField(decimal_places=2, default=2000, max_digits=12)),
                ('limite_api_requetes', models.IntegerField(default=60)),
                ('date_debut', models.DateTimeField(auto_now_add=True)),
                ('date_fin', models.DateTimeField(blank=True, null=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('utilisateur', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='licence', to='users.utilisateurbancaire')),
            ],
            options={
                'verbose_name': 'Licence',
                'verbose_name_plural': 'Licences',
            },
        ),
    ]
